/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package edu.cuc.ventanas;

import edu.cuc.math.Polinomio2;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author Jedabero
 */
public class VentanaPolinomio extends javax.swing.JFrame {

    /**
     * Creates new form VentanaPolinomio
     */
    public VentanaPolinomio() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        encunciadoLabel = new javax.swing.JLabel();
        coefAText = new javax.swing.JTextField();
        coefBText = new javax.swing.JTextField();
        coefCText = new javax.swing.JTextField();
        imgLabel = new javax.swing.JLabel();
        resolveButton = new javax.swing.JButton();
        resultadoLabel = new javax.swing.JLabel();
        txtResult = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Polinomio de segundo grado");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setName("VentanaPolinomio"); // NOI18N

        encunciadoLabel.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        encunciadoLabel.setText("Digite los valores de los coeficientes de la ecuación cuadrática.");

        coefAText.setColumns(3);
        coefAText.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N

        coefBText.setColumns(3);
        coefBText.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N

        coefCText.setColumns(3);
        coefCText.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N

        imgLabel.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        imgLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edu/cuc/img/6b626edf41c39246961f6b01e54a8ebe.png"))); // NOI18N

        resolveButton.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        resolveButton.setMnemonic('R');
        resolveButton.setText("Resolver");
        resolveButton.setToolTipText("Resuelve la ecuación cuadratica.");
        resolveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resolveButtonActionPerformed(evt);
            }
        });

        resultadoLabel.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        resultadoLabel.setText("Resultado:");

        txtResult.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        txtResult.setToolTipText("El resultado");
        txtResult.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(encunciadoLabel)
                .addGap(22, 22, 22))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(158, 158, 158)
                        .addComponent(resolveButton))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addComponent(coefAText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(coefBText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(coefCText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(63, 63, 63)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(imgLabel)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(24, 24, 24)
                                .addComponent(resultadoLabel)
                                .addGap(18, 18, 18)
                                .addComponent(txtResult, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(encunciadoLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(coefAText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(coefBText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(coefCText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(imgLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                .addComponent(resolveButton)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(resultadoLabel))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(7, 7, 7)
                        .addComponent(txtResult, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void resolveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resolveButtonActionPerformed
        Polinomio2 poli;
        
        int A = Integer.parseInt(coefAText.getText());
        int B = Integer.parseInt(coefBText.getText());
        int C = Integer.parseInt(coefCText.getText());
        
        try {
            poli = new Polinomio2(A, B, C);
        } catch (Exception ex) {
            poli = null;
            Logger.getLogger(VentanaPolinomio.class.getName()).log(Level.SEVERE, null, ex);
        }
        poli.calcRoots();
        txtResult.setText("<html>Raiz1: "+poli.root1+"<p>Raiz2: "+poli.root2);
        
    }//GEN-LAST:event_resolveButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new VentanaPolinomio().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField coefAText;
    private javax.swing.JTextField coefBText;
    private javax.swing.JTextField coefCText;
    private javax.swing.JLabel encunciadoLabel;
    private javax.swing.JLabel imgLabel;
    private javax.swing.JButton resolveButton;
    private javax.swing.JLabel resultadoLabel;
    private javax.swing.JLabel txtResult;
    // End of variables declaration//GEN-END:variables
}
